interfaces:
  leaf1:
    lo:
      ip: '10.100.1.3/32'
      ospf:
        state: 'present'
        passive: 'yes'
    swp1:
      alias: 'uplink to spine1'
      ipv4: '10.101.3.2/30'
      ospf:
        state: 'present'
    swp2:
      alias: 'uplink to spine2'
      ipv4: '10.102.3.2/30'
      ospf:
        state: 'present'
    vlan1:
      alias: 'primary mgmt vlan for servers'
      ipv4: '10.1.1.1/24'
      bridgeports: 'swp3-20'
      ospf:
        state: 'present'
        passive: 'yes'
    vlan2:
      alias: 'primary data vlan for servers'
      ip: '10.1.2.1/24'
      bridgeports: 'swp3-20.2'
      ospf:
        state: 'present'
        passive: 'yes'
    vlan3:
      alias: 'primary control vlan for servers'
      ip:  '10.1.3.1/24'
      bridgeports: 'swp3-20.3'
      ospf:
        state: 'present'
        passive: 'yes'
  leaf2:
    lo:
      ip: '10.100.1.4/32'
      ospf:
        state: 'present'
        passive: 'yes'
    swp1:
      alias: 'uplink to spine1'
      ipv4: '10.101.4.2/30'
      ospf:
        state: 'present'
    swp2:
      alias: 'uplink to spine2'
      ipv4: '10.102.4.2/30'
      ospf:
        state: 'present'
    vlan11:
      alias: 'backup mgmt vlan for servers'
      ip: '10.1.11.1/24'
      bridgeports: 'swp3-20'
      ospf:
        state: 'present'
        passive: 'yes'
    vlan12:
      alias: 'backup data vlan for servers'
      ip: '10.1.12.1/24'
      bridgeports: 'swp3-20.2'
      ospf:
        state: 'present'
        passive: 'yes'
    vlan13:
      alias: 'backup control vlan for servers'
      ip:  '10.1.13.1/24'
      bridgeports: 'swp3-20.3'
      ospf:
        state: 'present'
        passive: 'yes'
